import { Button } from "@mui/material";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";

const Home = (props) => {
  const router = useRouter();

  return (
    <>
      <div className="flex flex-wrap items-center bg-[#FF8370]">
        <div className="w-full sm:w-1/2 text-center sm:px-6">
          <h1 className="text-3xl text-gray-900 font-semibold">
            Generosity is a Way of Life
          </h1>
          <h3 className="text-2xl text-gray-500 font-medium">
            Join Oodles and Start Giving
          </h3>
          <div className="mt-6 text-xl">
            Oodles is an application bringing restaurants and non-profit
            organizations together with the common goal of eliminating food
            waste. Restaurant owners can use our application to donate specified
            food products to non-profit organizations seeking food donations.
            While Non-profit organizations in search of donations can use our
            application to find and contact local restaurants offering food
            items.
          </div>
        </div>

        <div className="w-full sm:w-1/2">
          <Image
            src="/oodlesHero.png"
            alt="Oodles Landing Page Image"
            width="100%"
            height="100%"
            layout="responsive"
            objectFit="contain"
          />
        </div>
      </div>

      <div className="mx-auto py-32 bg-[#00B1B0]">
        <header className="text-center">
          <h1 className="text-5xl text-gray-900 font-bold whitespace-pre-line leading-hero">
            Our Mission
          </h1>
          <h3 className="text-2xl text-gray-500 font-medium">
            What is Life Without Purpose
          </h3>
          <div className="text-2xl mt-4 mb-16">
            Oodles means abundance, and at Oodles we believe no food should go
            to waste. Our mission is to eliminate food waste generated by
            restaurants.
          </div>

          <Link href="/account/register">
            <Button variant="contained" sx={{ backgroundColor: "#E42256" }}>
              Register
            </Button>
          </Link>
        </header>
      </div>

      {/* <div className="flex flex-wrap items-center flex-row-reverse">
        <div className="w-full sm:w-1/2 text-center sm:px-6">
          <h1 className="text-3xl text-gray-900 font-semibold">Our Mission</h1>
          <h3 className="text-2xl text-gray-500 font-medium">
            What is Life Without Purpose
          </h3>
          <div className="mt-6 text-xl">
            Oodles means abundance, and at Oodles we believe no food should go
            to waste. Our mission is to eliminate food waste generated by
            restaurants.
          </div>
        </div>

        <div className="w-full sm:w-1/2">
          <Image
            src="/oodlesHero.png"
            alt="Oodles Landing Page Image"
            width="100%"
            height="100%"
            layout="responsive"
            objectFit="contain"
          />
        </div>
      </div> */}
    </>
  );
};

export default Home;
